### ISSUE TITLE
Does this tool work with polygons? 

### ISSUE THREAD

**Issue by jeffjb4488** [chi-initiative/LeafletSlider-tutorial#4]
I am using this tool on my map (https://github.com/jeffjb4488/GeoJASON_test) to show change over time. I initially wanted to use the time slider tool with a geojson file with polygon shapes, but I simply could not make it work. I eventually gave up and used static polygons and added points connected to the time slider tool. I am adding this comment here to see if there was any way to make the slider work with polygons that I missed or if that could could be added.

Thank you,
Jeff

**Comment by geyerbri** [comment]
Hi Jeff,

I am assuming what you are asking about is creating a map with a slider, where increasing/decreasing the slider shows/hides polygons, based upon whatever time is associated with them? Is this similar to what you're looking to do?: https://geyerbri.github.io/polygontest/polygons.html

If it is, take a look at the working code to see how to adapt for your specific project: https://github.com/geyerbri/polygontest/blob/master/polygons.html

\- Brian

**Comment by jeffjb4488** [comment]
O wow! This is amazing Brian, thank you! I struggle with this for so long. I will look over your code and see how it all works. Thank you!

Jeff
________________________________

**Comment by jeffjb4488** [comment]
Brian, do you have an idea of how I would add a div container to the end of the time stamp container? Or to change the date display in the container to current the range of slider? 

Sort of like in this example? http://nyc.crashmapper.com/11/8/14/2/standard/collisions/2/10/40.644/-73.888.

**Comment by geyerbri** [comment]
Looking at that example via html inspection, I don't recognize the index file's structure. But it looks to me to be some kind of javascript framework. The slider's structure is defined in the html's `<head>`, in a script, as a chunk of nested div containers:

```html
<script type="text/html" id="sliderTemplate">
  <div id="slider-current">
    <span class="start-time"></span>-<span class="end-time"></span>
  </div>
  <div class="help">Travel through time ↓</div>
  <div id="slider-min"></div><div id="slider"></div><div id="slider-max"></div>
</script>
```

There's code in crashmapper.css to act on these containers as well (which makes sense). But because I don't know the framework being used I don't know how the site actually utilizes the script - and all of the other 8 script blocks in `<head>` that contain html like this - to construct the page.

Your best bet is to probably either 1) alter the LeafletSlider.js file to create the slider layout that you want, from that location; or 2) look into jquery's documentation about how sliders are constructed and how you might write a small block of javascript in the html file to override/alter the LeafletSlider-produced slider.

**Comment by jeffjb4488** [comment]
Thank you Brian! I messed around with the leafletslider.js file based on this example (https://stackoverflow.com/questions/33165308/how-to-get-start-and-end-of-a-leaflet-slider?newreg=0cad6c6247b24de58562d3da64fab5c3) and have made some progress - the date elements now appear. However, I cannot figure out how to get them to update. My github is https://github.com/jeffjb4488/GeoJASON_test. 

Any ideas?

**Comment by geyerbri** [comment]
Apologies, but my only suggestion would be for you to look at the crashmapper version to see how it updates them, then try to adapt that. Since that seems to be what the responding person did on that stackoverflow question, that's likely your best bet for comparing what you've done to something that's working to figure out your way forward.

**Comment by jeffjb4488** [comment]
No problem - thank you for your help through all of this. I messed around with it a bit more and got the elements working and looking nice - [http://historic-highlands.com/] (http://historic-highlands.com/ ). Thank you!
